name: Build Chlonium

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Framework 4.5.1 Developer Pack
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/1/6/7/167f0d79-9317-48ae-aedb-17120579f8e2/NDP451-KB2858728-x86-x64-AllOS-ENU.exe" -OutFile "ndp451.exe"
          Start-Process .\ndp451.exe -ArgumentList "/quiet", "/norestart" -Wait

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore Chlonium.sln

      - name: Build solution
        run: msbuild Chlonium.sln /p:Configuration=Release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Chlonium-executable
          path: ./Chlonium/bin/Release/Chlonium.exe
