name: Build Chlonium

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Framework 4.5.1 Developer Pack
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/9/6/0/96075294-6820-4f01-924a-474e0023e407/NDP451-KB2861696-x86-x64-DevPack.exe" -OutFile "ndp451.exe"
          Start-Process .\ndp451.exe -ArgumentList "/quiet", "/norestart" -Wait

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore Chlonium.sln

      - name: Build solution
        run: msbuild Chlonium.sln /p:Configuration=Release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Chlonium-executable
          path: ./Chlonium/bin/Release/Chlonium.exe
